### PR TITLE
Add LICENSE File

### PR DESCRIPTION
**Pull request by richford**
Adds Apache 2 license.

I left the copyright holder's name and year empty. I assume the year will be 2020. But not sure what to put for the copyright holder's name. I noticed that it's blank in the main [dmriprep repo](https://github.com/nipreps/dmriprep/blob/master/LICENSE) as well. Should we say "dmriprep developers" or some such thing?

### CODE REVIEW

**Comment by richford** [comment]
Resolves #8

**Comment by arokem** [comment]
I would say "nipreps developers" to be a bit more general, here as well as in dmriprep

**Comment by arokem** [comment]
Interestingly, I can't merge this PR.  Apparently, I don't have write permissions here.

**Comment by oesteban** [comment]
I'll check that and give you permissions

**Pull request merged**
